apiVersion: v1
data:
  FNames.txt: |-
    Jim
    Justin
    Chuck
    Bernard
    Mike
    Syed
    Liam
    Noah
    William
    James
    Logan
    Emma
    Olivia
    Ava
    Isabella
    Sophia
    Mia
    Benjamin
    Mason
    Elijah
    Oliver
    Jacob
    Lucas
    Michael
    Alexander
    Elizabeth
    Ethan
    Avery
    Daniel
    Sofia
    Matthew
    Ella
    Aiden
    Madison
    Henry
    Scarlett
    Joseph
    Victoria
    Jackson
    Aria
    Samuel
    Grace
    Sebastian
    Chloe
    David
    Camila
    Carter
    Penelope
    Wyatt
    Riley
    Jayden
    Layla
    John
    Lillian
    Owen
    Nora
    Dylan
    Zoey
    Luke
    Mila
    Gabriel
    Aubrey
    Anthony
    Hannah
    Isaac
    Lily
    Grayson
    Addison
    Jack
    Eleanor
    Julian
    Natalie
    Levi
    Luna
    Christopher
    Savannah
    Joshua
    Brooklyn
    Andrew
    Leah
    Lincoln
    Zoe
    Mateo
    Stella
    Ryan
    Hazel
    Jaxon
    Ellie
    Nathan
    Paisley
    Aaron
    Audrey
    Isaiah
    Skylar
    Thomas
    Violet
    Charles
    Claire
    Caleb
    Bella
    Josiah
    Aurora
    Christian
    Lucy
    Hunter
    Anna
    Eli
    Samantha
    Jonathan
    Caroline
    Connor
    Genesis
    Landon
    Aaliyah
    Adrian
    Kennedy
    Asher
    Kinsley
    Cameron
    Allison
    Leo
    Maya
    Theodore
    Sarah
    Jeremiah
    Madelyn
    Hudson
    Adeline
    Robert
    Alexa
    Easton
    Ariana
    Nolan
    Elena
    Nicholas
    Gabriella
    Ezra
    Naomi
    Colton
    Alice
    Angel
    Sadie
    Brayden
    Hailey
    Jordan
    Eva
    Dominic
    Emilia
    Austin
    Autumn
    Ian
    Quinn
    Adam
    Nevaeh
    Elias
    Piper
    Jaxson
    Ruby
    Greyson
    Serenity
    Jose
    Willow
    Ezekiel
    Everly
    Carson
    Cora
    Evan
    Kaylee
    Maverick
    Lydia
    Bryson
    Aubree
    Jace
    Arianna
    Cooper
    Eliana
    Xavier
    Peyton
    Parker
    Melanie
    Roman
    Gianna
    Jason
    Isabelle
    Santiago
    Julia
    Chase
    Valentina
    Sawyer
    Nova
    Gavin
    Clara
    Leonardo
    Vivian
    Kayden
    Ayden
    Jameson
    Charlotte
    Amelia
    Evelyn
    Abigail
    Harper
    Emily
    Reagan
    Mackenzie
    Madeline
  LNames.txt: |-
    Tyrrell
    Mosher
    Tison
    Jarae
    Echevarria
    Shaaf
    Smith
    Johnson
    Williams
    Jones
    Brown
    Davis
    Miller
    Wilson
    Moore
    Taylor
    Anderson
    Thomas
    Jackson
    White
    Harris
    Martin
    Thompson
    Garcia
    Martinez
    Robinson
    Clark
    Rodriguez
    Lewis
    Lee
    Walker
    Hall
    Allen
    Young
    Hernandez
    King
    Wright
    Lopez
    Hill
    Scott
    Green
    Adams
    Baker
    Gonzalez
    Nelson
    Carter
    Mitchell
    Perez
    Roberts
    Turner
    Phillips
    Campbell
    Parker
    Evans
    Edwards
    Collins
    Stewart
    Sanchez
    Morris
    Rogers
    Reed
    Cook
    Morgan
    Bell
    Murphy
    Bailey
    Rivera
    Cooper
    Richardson
    Cox
    Howard
    Ward
    Torres
    Peterson
    Gray
    Ramirez
    James
    Watson
    Brooks
    Kelly
    Sanders
    Price
    Bennett
    Wood
    Barnes
    Ross
    Henderson
    Coleman
    Jenkins
    Perry
    Powell
    Long
    Patterson
    Hughes
    Flores
    Washington
    Butler
    Simmons
    Foster
    Gonzales
    Bryant
    Alexander
    Russell
    Griffin
    Diaz
    Hayes
  app-config.properties: >-
    fnames.file=/deployments/config/FNames.txt

    lnames.file=/deployments/config/LNames.txt

    incident.service=incident-service.naps-emergency-response.svc
    incident.port=8080
    incident.uri=/incidents

    enabled=false
kind: ConfigMap
metadata:
  name: disaster-simulator
